### ISSUE TITLE
Backbone dihedral features

### ISSUE THREAD

**Issue by ld139** [Kuhlman-Lab/PIPPack#3]
Thanks for your meaningful work. 
I am wondering how you calculate the dihedral angle of the protein termini residues as features. It seems that NaN values may occur.

**Comment by nzrandol** [comment]
Thanks for your interest! You're absolutely right. NaNs will occur wherever there are chain breaks, including the terminal residues. After I compute the dihedrals, I transform the NaNs into 0s [here](https://github.com/Kuhlman-Lab/PIPPack/blob/9aea0a201ced4b7fcaeee7619ece6d45fdc754ae/data/top2018_dataset.py#L361) so that it doesn't affect the model.
